on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    
    # From r-lib/actions
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy: 
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'devel'}
          - {os: macOS-latest, r: 'release'}
          - {os: macOS-latest, r: 'devel'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      
      - uses: r-lib/actions/setup-tinytex@v1
        if: runner.os != 'Windows'
      
      - name: Install GDAL + qpdf
        if: runner.os != 'Windows'
        run: |
          sudo apt-get install libgdal-dev
          sudo apt-get install qpdf
          
      # From r-lib/actions
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-
          
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Check
        continue-on-error: true
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        
      - name: Check as CRAN
        env: 
          NOT_CRAN: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual","--as-cran"), error_on = "error")
        shell: Rscript {0}
        
      #- name: Upload check results
      #  if: failure()
      #  uses: actions/upload-artifact@master
      #  with:
      #    name: ${{ runner.os }}-r${{ matrix.config.r }}-results
      #    path: check
